git add README
git add MANUAL
git add Makefile
git add bill.c
git add bill.h
git add cbill.c
git add clean.h
git add clogin.c
git add common.c
git add common.h
git add cpos.c
git add cpos.h
git add cprog.c
git add creport.c
git add git_add.sh
git add key.h
git add menu.c
git add menu.h
git add morder.c
git add mpos.c
git add order.c
git add prog.c
git add prog.h
git add report.c
