		/* key.h macros for documentation */

# define FLD_CHAR  	1
# define HOT_KEY   	2
# define AFLD_CHAR 	3
# define OK_KEY    	4
# define TAB_KEY   	5
# define DOWN_KEY  	6
# define UP_KEY    	7
# define BSP_KEY   	8
# define KEY_ESC   	9
# define ENCRYPT   	10
# define ALPHA     	31
# define ALNUM     	2
# define DIGIT     	3
# define CHECK     	4
# define UPPER     	5
# define LOWER     	6
# define DASH			 	7
# define ACTION	   	8
# define AMOUNT    	9
# define PASSWD	   	10
# define DISP				11
# define MATH				12
# define BAMOUNT    14	
# define DATE				15	
# define CR_KEY   	'\n'
# define QKEY     	'?'
# define EMERGE   	'\0'
# define KEY_TAB		'\t'
# define DOT			 	'.'
# define ESC_KEY	  27

# define CTRL_AA		1
# define CTRL_BB		2	
# define CTRL_CC		3		
# define CTRL_DD		4		
# define CTRL_EE		5		
# define CTRL_FF		6		
# define CTRL_GG		7		
# define CTRL_HH		8		
# define CTRL_II		9		
# define CTRL_JJ		10		
# define CTRL_KK		11	
# define CTRL_LL		12	
# define CTRL_MM		13	
# define CTRL_NN		14	
# define CTRL_OO		15
# define CTRL_PP		16	
# define CTRL_QQ		17	
# define CTRL_RR		18	
# define CTRL_SS		19	
# define CTRL_TT		20	
# define CTRL_UU		21	
# define CTRL_VV		22	
# define CTRL_WW		23	
# define CTRL_XX		24	
# define CTRL_YY		25
# define CTRL_ZZ		26

